[versions]
kotlin = "1.9.21"
ktlint = "1.1.0"
gradle-ktlint = "12.0.3"
dokka = "1.9.10"
nexus-publish = "1.3.0"
typesafe-config = "1.4.3"
kotest = "5.8.0"
jgitver = "0.9.1"
binary-compatibility-validator = "0.13.2"

[libraries]
typesafe-config = { group = "com.typesafe", name = "config", version.ref = "typesafe-config" }
kotest = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotest" }
ktlint = { group = "com.pinterest.ktlint", name = "ktlint-bom", version.ref = "ktlint" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradle-ktlint" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
jgitver = { id = "fr.brouillard.oss.gradle.jgitver", version.ref = "jgitver" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
