[versions]
kotlin = "2.3.0"
ktlint = "1.8.0"
gradle-ktlint = "14.0.1"
dokka = "2.1.0"
nexus-publish = "2.0.0"
typesafe-config = "1.4.5"
kotlinx-serialization = "1.10.0"
kotest = "5.9.1"
mockk = "1.14.9"
jgitver = "0.9.1"
binary-compatibility-validator = "0.18.1"

[libraries]
assertj = { module = "org.assertj:assertj-bom", version = "3.27.7" }
typesafe-config = { group = "com.typesafe", name = "config", version.ref = "typesafe-config" }
kotlinx-serialization-hocon = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-hocon", version.ref = "kotlinx-serialization" }
kotest = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
junit = { module = "org.junit:junit-bom", version = "6.0.2" }
ktlint = { group = "com.pinterest.ktlint", name = "ktlint-bom", version.ref = "ktlint" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradle-ktlint" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
jgitver = { id = "fr.brouillard.oss.gradle.jgitver", version.ref = "jgitver" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
